---
title: "Datos"
author: "C"
date: "2024-05-01"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(dplyr)
library(xtable)
```

```{r, message=FALSE, warning=FALSE}
fondoB <- read_excel("BD Pensionados.xlsx", sheet = "Fondo B", range = cell_cols(1:8))
planilla<-read_excel("BD Pensionados.xlsx", sheet = "Fondo B", range = "K2", col_names = FALSE)
planilla<- planilla$...1

fondoB[] <- lapply(fondoB, function(x) if(is.character(x)) as.factor(x) else x)

fondoB$`Rige de la Pensión`<- as.Date(fondoB$`Rige de la Pensión`)
fondoB$FEC_NAC<- as.Date(fondoB$FEC_NAC)


summary(fondoB)
```

```{r}
data_vejez <- fondoB[fondoB$COD_TIPO_PENSION == "Vejez", ]
data_sucesion <- fondoB[fondoB$COD_TIPO_PENSION == "Sucesión", ]
data_invalidez <- fondoB[fondoB$COD_TIPO_PENSION == "Invalidez", ]
```

# Distribucion por sexo
```{r}
ggplot(fondoB, aes(x = SEXO, fill = COD_TIPO_PENSION)) + 
  geom_bar(position = "dodge", stat = "count") +
   geom_text(stat = 'count', aes(label = after_stat(count)), vjust = -0.5, position = position_dodge(width = 0.9), size = 3) +
  labs(title = "Distribución por sexo",
       x = "Sexo",
       y = "Cantidad") +
  scale_fill_brewer(palette = "Set1") +  
  theme_minimal()
```

```{r}

fondoB<- fondoB%>%
  mutate(edad = interval(start = fondoB$FEC_NAC, end = today()) / years(1)) %>%
  mutate(edad = round(edad, 2))

fondoB<- fondoB%>%
  mutate(antiguedad = interval(start = fondoB$`Rige de la Pensión`, end = today()) / years(1)) %>%
  mutate(antiguedad = round(antiguedad, 2))

fondoB<- fondoB%>%
  mutate(EsperanzaVida = ifelse(SEXO == "F", 79.81 - edad,
                         ifelse(SEXO == "M", 74.42 - edad, NA))) %>% 
  mutate(EsperanzaVida = ifelse(EsperanzaVida<0, 1,EsperanzaVida))


descripcion <- fondoB %>% select(SEXO, MONTO, edad, antiguedad)
summary(descripcion)

```

# Posibles graficos para la edad

```{r}
ggplot(fondoB, aes(x = COD_TIPO_PENSION, y = edad, fill = COD_TIPO_PENSION)) +
  geom_violin(trim = FALSE) +
  labs(title = "Distribución etaria por tipo de pensión",
       x = "Pensión",
       y = "Edad") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()
```
```{r}
ggplot(fondoB, aes(x = edad, fill = COD_TIPO_PENSION)) +
  geom_density(alpha = 0.6) +
  labs(title = "Distribución etaria por tipo de pensión",
       x = "Pensión",
       y = "Edad") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()
```

```{r}
ggplot(fondoB, aes(x = edad)) +
  geom_histogram(bins = 20, fill = "skyblue", color = "black") +
  facet_wrap(~ COD_TIPO_PENSION) +
  labs(title = "Distribución etaria por tipo de pensión",
       x = "Pensión",
       y = "Edad") +
  scale_fill_brewer(palette = "Set1") +
  theme_minimal()
```


```{r}
hist(fondoB$edad, breaks = 20, main ="", xlab = "Edad", ylab = "Frecuencia", col = "#3A8DCC")

```

```{r, message=FALSE, warning=FALSE}
fondoB_Act <- read_excel("BD Activos.xlsx", sheet = "Fondo B", range = cell_cols(1:363))
fondoB_Act[] <- lapply(fondoB_Act, function(x) if(is.character(x)) as.factor(x) else x)
```
# Reescribe los nombres de las columnas por las respectivas fechas
```{r}
num_cols <- ncol(fondoB_Act)
fechas <- seq(as.Date("1994-01-01"), by = "month", length.out = num_cols)
nuevos_nombres <- format(fechas)

for (col in 1:ncol(fondoB_Act)) {
  if (col <= 3){
  }
  else {
    colnames(fondoB_Act)[col] <- nuevos_nombres[col-3]
  }
}
```
# Calcula la edad según la fecha de nacimiento, devuelve gráficos
```{r}
fondoB_Act$Fec.Nac <- ymd(fondoB_Act$Fec.Nac)
fecha_actual <- as.Date("2023-12-31")
fondoB_Act$Edad <- as.numeric(difftime(fecha_actual, fondoB_Act$Fec.Nac, units = "days")) / 365.25


summary(fondoB_Act$Edad)

hist(fondoB_Act$Edad, breaks = 10, main = "Histograma de Edades", xlab = "Edad", ylab = "Frecuencia", col = "#3A8DCC")


```

```{r}
funcion_graf_pensionados <- function(tipo_pension) {
  fondo_T <- subset(fondoB, COD_TIPO_PENSION == tipo_pension)
  
  edades_mujeres <- fondo_T$edad[fondo_T$SEXO == "F"]
  edades_hombres <- fondo_T$edad[fondo_T$SEXO == "M"]
  
  # Calculamos los límites para el histograma
  min_edad <- min(min(edades_mujeres, na.rm = TRUE), min(edades_hombres, na.rm = TRUE))
  max_edad <- max(max(edades_mujeres, na.rm = TRUE), max(edades_hombres, na.rm = TRUE))
  breaks <- seq(min_edad, max_edad + 10, by = 10)
  
  # Creamos los histogramas
  hist(edades_mujeres, breaks = breaks, main = "", xlab = "Edad", ylab = "Frecuencia", col = "#3A8DCC", ylim = c(0, max(max(hist(edades_mujeres, breaks = breaks, plot = FALSE)$counts), max(hist(edades_hombres, breaks = breaks, plot = FALSE)$counts))))
  hist(edades_hombres, breaks = breaks, add = TRUE, col = "#FF6EC7", density = 40)
  
  # Agregamos la leyenda
  legend("topright", legend = c("Mujeres", "Hombres"), fill = c("#3A8DCC", "#FF6EC7"))
}

funcion_graf_pensionados("Invalidez")
funcion_graf_pensionados("Sucesión")
funcion_graf_pensionados("Vejez")

```

```{r}
edades_mujeres <- fondoB_Act$Edad[fondoB_Act$Sexo == "F"]
edades_hombres <- fondoB_Act$Edad[fondoB_Act$Sexo == "M"]
hist(edades_mujeres, breaks = 10, main = "", xlab = "Edad", ylab = "Frecuencia", col = "#3A8DCC", ylim = c(0, max(hist(edades_mujeres, breaks = 10)$counts, hist(edades_hombres, breaks = 10)$counts)))

hist(edades_hombres, breaks = 10, add = TRUE, col = "#FF6EC7", density = 40)
legend("topright", legend = c( "Hombres","Mujeres"), fill = c("#3A8DCC", "#FF6EC7"))
```


```{r}
boxplot(fondoB_Act$Edad, main = "Diagrama de Caja de Edades", ylab = "Edad")

boxplot(Edad ~ Sexo, data = fondoB_Act, main = "Diagrama de Caja de Edades por Sexo", ylab = "Edad", col = c("#3A8DCC", "#FF6EC7"))


```
# Calcula la antiguedad y grafica la distribucion
```{r}
calcular_antiguedad <- function(fila) {
  primera_fecha <- which.max(fila != 0)[1]
  if (is.na(primera_fecha)) {
    return(NA)  # Si nunca ha pagado, la antigüedad es NA
  } else {
    
    fecha_inicio <- as.Date(names(fila)[primera_fecha], format = "%Y-%m-%d")
    fecha_actual <- as.Date("2023-12-31")  # Fecha actual
    antiguedad <- as.numeric(difftime(fecha_actual, fecha_inicio, units = "days")) / 365.25
    return(antiguedad)
  }
}

fondoB_Act$Antiguedad <- apply(fondoB_Act[, -c(1:3)], 1, calcular_antiguedad)


summary(fondoB_Act$Antiguedad)

hist(fondoB_Act$Antiguedad, breaks = 10, main = "Histograma de Antigüedad", xlab = "Antigüedad", ylab = "Frecuencia", col = "#3A8DCC")

frecuencias <- hist(fondoB_Act$Antiguedad, breaks = 10, plot = FALSE)$counts


boxplot(fondoB_Act$Antiguedad, main = "Diagrama de Caja de Edades", ylab = "Antiguedad")
```

# Resumen estadístico de los datos demográficos 
```{r}
columnasDatos <- fondoB_Act[, c("Fec.Nac", "Edad", "Antiguedad", "Sexo")]

summary(columnasDatos)
```
# Gtaficos de sexo
```{r}
tabla_sexo <- table(fondoB_Act$Sexo)
print(tabla_sexo)

barplot(tabla_sexo, main = "Distribución de Género", xlab = "Género", ylab = "Frecuencia", col = "#3A8DCC")


```


```{r, message=FALSE, warning=FALSE}
fondoB_Fin <- read_excel("BD Financiero.xlsx", sheet = "Datos Historicos Fondo B", range = cell_cols(1:6))
```

```{r}
# Inicializar la columna de reservas
fondoB_Fin$Reservas <- numeric(nrow(fondoB_Fin))

# Calcular reservas para el primer mes
fondoB_Fin$Reservas[1] <- (fondoB_Fin$Activo[1] + fondoB_Fin$"Plusvalía/Minusvalias"[1] + fondoB_Fin$"Cotizaciones Netas"[1] - fondoB_Fin$"Pago de Pensiones"[1])/1000000

# Calcular reservas para los meses siguientes
for (i in 2:nrow(fondoB_Fin)) {
  fondoB_Fin$Reservas[i] <- (fondoB_Fin$Reservas[i-1]*1000000 + 
                            fondoB_Fin$"Plusvalía/Minusvalias"[i] + 
                            fondoB_Fin$"Cotizaciones Netas"[i] - 
                            fondoB_Fin$"Pago de Pensiones"[i])/1000000
}

# Ver el dataframe actualizado
print(fondoB_Fin)
```
```{r}
# Crear el histograma de la columna Reservas
# Crear el gráfico de líneas de las reservas en orden temporal
plot(fondoB_Fin$Período, fondoB_Fin$Reservas, 
     type = "o", # Línea y puntos
     main = "Evolución de las Reservas en Unidades de Millón", 
     xlab = "Periodo", 
     ylab = "Reservas (Millones)", 
     col = "blue", 
     lwd = 2, # Grosor de la línea
     pch = 16) # Tipo de punto

# Opcional: Rotar etiquetas del eje x para mejor visibilidad
# if needed
par(las=2)
```

```{r}
# Crear el boxplot de las reservas
boxplot(fondoB_Fin$Reservas,
        main = "Distribución de las Reservas en Unidades de Millón",
        ylab = "Reservas (Millones)",
        col = "lightblue")
```

```{r}
summary(fondoB_Fin$Reservas)
```

```{r}
# Ajustar un modelo de regresión lineal
modelo <- lm(Reservas ~ as.numeric(Período), data = fondoB_Fin)
summary(modelo)

# Gráfico con la línea de regresión
plot(fondoB_Fin$Período, fondoB_Fin$Reservas, 
     main = "Evolución de las Reservas con Línea de Tendencia", 
     xlab = "Periodo", 
     ylab = "Reservas (Millones)", 
     col = "blue", 
     pch = 16)
abline(modelo, col = "red")
```

```{r}
# Redondear hacia abajo las edades

fondoB_Act <- fondoB_Act %>%
  mutate(Edad = floor(Edad))

fondoB <- fondoB %>%
  mutate(edad = floor(edad))


tabla_estados <- data.frame(
  edad = 0:115
)

# Contar los activos por edad
activos <- fondoB_Act %>%
  group_by(Edad) %>%
  summarise(activo = n()) %>%
  rename(edad = Edad)

# Contar los otros estados por edad
estados <- fondoB %>%
  group_by(edad, COD_TIPO_PENSION) %>%
  summarise(count = n()) %>%
  spread(COD_TIPO_PENSION, count, fill = 0) %>%
  rename(invalidez = Invalidez, vejez = Vejez, sucesion = Sucesión)

# Combinar los resultados en la tabla de resultados
tabla_estados <- tabla_estados %>%
  left_join(activos, by = "edad") %>%
  left_join(estados, by = "edad") 
#%>%eplace(is.na(.), 0)


print(tabla_estados)



```

